FROM gradle:8.12.1-jdk21-alpine AS builder
USER gradle
WORKDIR /tests
COPY --chown=gradle:gradle build.gradle  ./
RUN gradle cacheAllDependencies --no-daemon


FROM gradle:8.12.1-jdk21-alpine
USER gradle
WORKDIR /tests
COPY --from=builder /home/gradle/.gradle /home/gradle/.gradle
COPY --from=builder /tests/build.gradle ./
RUN mkdir -p /home/gradle/.java/.userPrefs && \
    chown -R gradle:gradle /home/gradle/.java &&\
    chmod -R 755 /tests



